consul:
    image: progrium/consul:latest
    command: >
      -server
      -bootstrap-expect 1
      -ui-dir /ui
    mem_limit: 256m
    ports:
    - 53
    - 8300
    - 8301
    - 8302
    - 8400
    - 8500
    - 8600
    restart: always

nginx:
    image: autopilotpattern/cloudflare-demo-nginx
    mem_limit: 512m
    ports:
    - 80
    links:
    - consul:consul
    restart: always
    environment:
    - CONTAINERBUDDY=file:///opt/containerbuddy/nginx.json
    command: >
      /opt/containerbuddy/containerbuddy
      nginx -g "daemon off;"

cloudflare:
    image: autopilotpattern/cloudflare
    mem_limit: 128m
    links:
    - consul:consul
    restart: always
    env_file: .env
    command: >
      /opt/containerbuddy/containerbuddy
      -config file:///opt/containerbuddy/cloudflare.json
