# a minimal Nginx container including containerbuddy and a simple virtulhost config
FROM nginx:latest

# add containerbuddy and all our configuration
ADD opt/containerbuddy /opt/containerbuddy/
ADD etc/nginx/conf.d /etc/nginx/conf.d/
